config/routes.rb
Rails.application.routes.draw do
  root 'session#new'
  
  post 'login', to: 'session#create' # I will get to it when there's authenctication
  delete 'logout', to: 'session#destroy'
  
  get 'download_po/:id', to: 'order#downloadPO', as: 'download_po'

  get 'order/invoice/:id', to: 'order#invoice', as: 'order_invoice'
  post 'order/invoice/:id', to: 'order#createInvoice', as: 'create_invoice'
  post 'order', to: 'order#index'
  
  resources :identity
  resources :order
  resources :invoices do
    resources :invoice_items
    get 'download', to: 'invoices#downloadInvoice'
    get 'send', to: 'invoices#sendInvoice'
  end

  # get 'invoice_items/index'
  # get 'invoice_items/show'
  # get 'invoice_items/edit'
  # get 'invoice_items/update'
  # get 'invoice_items/index'
  # get 'invoice_items/edit'
  # get 'invoice_items/update'
  # get 'invoice_items/show'  
  get 'download_invoice/:id', to: 'order#downloadInvoice', as: 'download_invoice'
  get 'send_invoice/:id', to: 'order#sendInvoice', as: 'send_invoice'
  # resources :invoice_items
  # get 'invoices/:id/invoice_items', to: 'invoices#invoice_items_list', as: 'invoice_items_list'
  # post 'order_filter', to: 'order#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
    before_action :authorize
    
    def index
        @invoices = current_user.invoice_list["Invoices"]

        @invoices.each do |invoice|
            if invoice["createDate"].present? || invoice["updateDate"].present?
                invoice["createDate"] = time_format(invoice["createDate"]) if invoice["createDate"].present?
                invoice["updateDate"] = time_format(invoice["updateDate"]) if invoice["updateDate"].present?
            end
        end
    end

    def show
        @invoice = current_user.invoice_id_get(params[:id])["Invoice"]
        @invoice["createDate"] = time_format(@invoice["createDate"]) if @invoice["createDate"].present?
        @invoice["updateDate"] = time_format(@invoice["updateDate"]) if @invoice["updateDate"].present?
    end

    def update;
    end

    def downloadInvoice
        # WE MUST USE AJAX HERE!!
        # purchaseOrderID = current_user.invoice_id_get(paras[:invoice_id])["Invoice"]["purchaseOrderID"]
        
        unless current_user.download_invoice(params[:invoice_id]).include? ("Error")
            file = current_user.download_invoice(params[:invoice_id])
            send_data file, filename: "INVOICE_ID_#{params[:invoice_id]}.xml", disposition: 'download'
            # redirect_to invoices_path
        else
            flash[:danger] = "No Invoice file found. Ensure that you create an Invoice first."
            redirect_to invoices_path
        end
    end

    def sendInvoice
        @invoice = current_user.invoice_send(params[:invoice_id])
        unless @invoice["Error"].present?
          flash[:success] = 'Invoice successfully sent'
        else
          flash[:danger] = "Ensure that you have created an Invoice before Sending an invoice to Coupa"
        end
        redirect_to invoices_path
    end

    private

    def time_format(time_string)
        temp_arr = time_string.split('T')
        temp_arr2 = temp_arr[1].split(':')
        temp_str = temp_arr[0] + ", " + temp_arr2[0] + ":" + temp_arr2[1]
        temp_str
    end 
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/dump.html.erb
<td>
<%= link_to identity_path(identity["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Show' do %>
    <i class="bi bi-arrows-fullscreen" style="padding: 0 10px !important;"></i>
<% end %>
</td>
<td>
<%= link_to edit_identity_path(identity["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Edit' do %>
    <i class="bi bi-pencil" style="padding: 0 10px !important;"></i>
<% end %>
</td>
<td>
<%= link_to identity_path(identity["ID"]), method: :delete, data: { toggle: 'tooltip', placement: "top", confirm: "Are you sure?" }, title: 'Delete' do %>
    <i class="bi bi-trash" style="padding: 0 10px !important;"></i>
<% end %>
</td>



<div class="col-md-2">
      <label for="inputTaxNumber" class="form-label">Tax Number</label>
      <%= text_field(:identity, :TaxNumber, value: @identity["TaxNumber"], placeholder: "Tax Number", class: "form-control", id: "inputTaxNumber") %>
    </div>
    <div class="col-md-5">
      <label for="inputRegisteredName" class="form-label">Registered Name</label>
      <%= text_field(:identity, :RegisteredName, value: @identity["RegisteredName"], placeholder: "Registered Name", class: "form-control", id: "inputRegisteredName") %>
    </div>
    <div class="col-md-5">
      <label for="inputTradingAs" class="form-label">Trading As</label>
      <%= text_field(:identity, :TradingAs, value: @identity["TradingAs"], placeholder: "Trading As", class: "form-control", id: "inputTradingAs") %>
    </div>
    <div class="col-md-3">
      <label for="inputTelephoneNumber" class="form-label">Telephone Number</label>
      <%= text_field(:identity, :TelephoneNumber, value: @identity["TelephoneNumber"], placeholder: "Telephone Number", class: "form-control", id: "inputTelephoneNumber") %>
    </div>
    <div class="col-md-2">
      <label for="inputPhysicalID" class="form-label">Physical ID</label>
      <%= number_field(:identity, :PhysicalID, value: @identity["PhysicalID"], placeholder: "Physical ID", class: "form-control", id: "inputPhysicalID") %>
    </div>
    <div class="col-md-2">
      <label for="inputPostalID" class="form-label">Postal ID</label>
      <%= text_field(:identity, :PostalID, value: @identity["PostalID"], placeholder: "Postal ID", class: "form-control", id: "inputPostalID") %>
    </div>
    <div class="col-md-4">
      <label for="inputTaxPrefix" class="form-label">Tax Prefix</label>
      <%= text_field(:identity, :TaxPrefix, value: @identity["TaxPrefix"], placeholder: "Tax Prefix", class: "form-control", id: "inputTaxPrefix") %>
    </div>
    <div class="col-md-4">
      <label for="inputTaxIndicator" class="form-label">Tax Indicator</label>
      <%= text_field(:identity, :TaxIndicator, value: @identity["TaxIndicator"], placeholder: "Tax Indicator", class: "form-control", id: "inputTaxIndicator") %>
    </div>
    <div class="col-md-4">
      <label for="inputTaxPercentage" class="form-label">Tax Percentage</label>
      <%= text_field(:identity, :TaxPercentage, value: @identity["TaxPercentage"], placeholder: "Tax Percentage", class: "form-control", id: "inputTaxPercentage") %>
    </div>
    <div class="col-md-4">
      <label for="inputRemitToName" class="form-label">Remit To Name</label>
      <%= text_field(:identity, :RemitToName, value: @identity["RemitToName"], placeholder: "Remit To Name", class: "form-control", id: "inputRemitToName") %>
    </div>
    <div class="col-md-4">
      <label for="inputRemitToStreet" class="form-label">Remit To Street</label>
      <%= text_field(:identity, :RemitToStreet, value: @identity["RemitToStreet"], placeholder: "Remit To Street", class: "form-control", id: "inputRemitToStreet") %>
    </div>
    <div class="col-md-4">
      <label for="inputRemitToCity" class="form-label">Remit To City</label>
      <%= text_field(:identity, :RemitToCity, value: @identity["RemitToCity"], placeholder: "Remit To City", class: "form-control", id: "inputRemitToCity") %>
    </div>
    <div class="col-md-4">
      <label for="inputRemitToPostalCode" class="form-label">Remit To Postal Code</label>
      <%= text_field(:identity, :RemitToPostalCode, value: @identity["RemitToPostalCode"], placeholder: "Remit To Postal Code", class: "form-control", id: "inputRemitToPostalCode") %>
    </div>
    <div class="col-md-4">
      <label for="inputRemitToCountryISOCode" class="form-label">Remit To Country ISO Code</label>
      <%= text_field(:identity, :RemitToCountryISOCode, value: @identity["RemitToCountryISOCode"], placeholder: "Remit To Country ISO Code", class: "form-control", id: "inputRemitToCountryISOCode") %>
    </div>
    <div class="col-md-4">
      <label for="inputRemitToCountry" class="form-label">Remit To Country</label>
      <%= text_field(:identity, :RemitToCountry, value: @identity["RemitToCountry"], placeholder: "Remit To Country", class: "form-control", id: "inputRemitToCountry") %>
    </div>
    <div class="col-md-4">
      <label for="inputRemitToAreaOrCityCode" class="form-label">Remit To Area Or City Code</label>
      <%= text_field(:identity, :RemitToAreaOrCityCode, value: @identity["RemitToAreaOrCityCode"], placeholder: "Remit To Area Or City Code", class: "form-control", id: "inputRemitToAreaOrCityCode") %>
    </div>
    <div class="col-md-4">
      <label for="inputRemitToPhoneNumber" class="form-label">Remit To Phone Number</label>
      <%= text_field(:identity, :RemitToPhoneNumber, value: @identity["RemitToPhoneNumber"], placeholder: "Remit To Phone Number", class: "form-control", id: "inputRemitToPhoneNumber") %>
    </div>
    <div class="col-md-4">
      <label for="inputRemitToFaxNumber" class="form-label">Remit To Fax Number</label>
      <%= text_field(:identity, :RemitToFaxNumber, value: @identity["RemitToFaxNumber"], placeholder: "Remit To Fax Number", class: "form-control", id: "inputRemitToFaxNumber") %>
    </div>
    <div class="col-md-4">
      <label for="inputRemitToTaxPrefix" class="form-label">Remit To Tax Prefix</label>
      <%= text_field(:identity, :RemitToTaxPrefix, value: @identity["RemitToTaxPrefix"], placeholder: "Remit To Tax Prefix", class: "form-control", id: "inputRemitToTaxPrefix") %>
    </div>
    <div class="col-md-4">
      <label for="inputRemitToTaxNumber" class="form-label">Remit To Tax Number</label>
      <%= text_field(:identity, :RemitToTaxNumber, value: @identity["RemitToTaxNumber"], placeholder: "Remit To Tax Number", class: "form-control", id: "inputRemitToTaxNumber") %>
    </div>
    <div class="col-md-4">
      <label for="inputURL" class="form-label">URL</label>
      <%= text_field(:identity, :URL, value: @identity["URL"], placeholder: "URL", class: "form-control", id: "inputURL") %>
    </div>
    <div class="col-md-4">
      <label for="inputFromName" class="form-label">From Name</label>
      <%= text_field(:identity, :FromName, value: @identity["FromName"], placeholder: "From Name", class: "form-control", id: "inputFromName") %>
    </div>
    <div class="col-md-4">
      <label for="inputFromStreet" class="form-label">From Street</label>
      <%= text_field(:identity, :FromStreet, value: @identity["FromStreet"], placeholder: "From Street", class: "form-control", id: "inputFromStreet") %>
    </div>
    <div class="col-md-4">
      <label for="inputFromCity" class="form-label">From City</label>
      <%= text_field(:identity, :FromCity, value: @identity["FromCity"], placeholder: "From City", class: "form-control", id: "inputFromCity") %>
    </div>
    <div class="col-md-4">
      <label for="inputFromPostalCode" class="form-label">From Postal Code</label>
      <%= text_field(:identity, :FromPostalCode, value: @identity["FromPostalCode"], placeholder: "From Postal Code", class: "form-control", id: "inputFromPostalCode") %>
    </div>
    <div class="col-md-4">
      <label for="inputFromCountryISOCode" class="form-label">From Country ISO Code</label>
      <%= text_field(:identity, :FromCountryISOCode, value: @identity["FromCountryISOCode"], placeholder: "From Country ISO Code", class: "form-control", id: "inputFromCountryISOCode") %>
    </div>
    <div class="col-md-4">
      <label for="inputFromCountry" class="form-label">From Country</label>
      <%= text_field(:identity, :FromCountry, value: @identity["FromCountry"], placeholder: "From Country", class: "form-control", id: "inputFromCountry") %>
    </div>
    <div class="col-md-4">
      <label for="inputFromTaxPrefix" class="form-label">From Tax Prefix</label>
      <%= text_field(:identity, :FromTaxPrefix, value: @identity["FromTaxPrefix"], placeholder: "From Tax Prefix", class: "form-control", id: "inputFromTaxPrefix") %>
    </div>
    <div class="col-md-4">
      <label for="inputFromTaxNumber" class="form-label">From Tax Number</label>
      <%= text_field(:identity, :FromTaxNumber, value: @identity["FromTaxNumber"], placeholder: "From Tax Number", class: "form-control", id: "inputFromTaxNumber") %>
    </div>
















.///
    <div id="identity-page" class="container-fluid mt-3">
    <% content_for :title, "Coupa Integration - Invoice Items" %>

    <h1>TABLE OF INVOICES ITEMS</h1>



    <div id="invoice-items-table" class="table-responsive-md table-responsive">    
        <table class="table table-striped table-hover">
            <thead class="table-dark">
                <th>ID</th>
                <th>invoiceID</th>
                <th>itemUnitOfMeasure</th>
                <th>quantity</th>
                <th>unitPrice</th>
                <th colspan="2"></th>
            </thead>

            <% if @invoice_items.present? %>
                <tbody id="table-body">
                    <% @invoice_items.each do |invoice_item| %>
                        <tr>
                            <td><%= invoice_item["id"] %></th>
                            <td><%= invoice_item["invoiceID"] %></td>
                            <td><%= invoice_item["itemUnitOfMeasure"] %></td>
                            <td><%= invoice_item["quantity"] %></td>
                            <td><%= invoice_item["unitPrice"] %></td>
                            <td>
                                <%= link_to invoice_invoice_item_path(invoice_item["id"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Show' do %>
                                    <i class="bi bi-arrows-fullscreen" style="padding: 0 10px !important;"></i>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to edit_invoice_invoice_item_path(invoice_item["id"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Edit' do %>
                                    <i class="bi bi-pencil" style="padding: 0 10px !important;"></i>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>                
            <% else %>
                <tbody>
                    <div style="position: absolute; margin-top: 7rem; width: 88%; display: flex; justify-content: center; align-items: center; height: 5rem; color: #ccc; background-color: white;">
                    No Invoice Items
                    </div>
                </tbody>           
            <% end %>
        </table>
    </div>
    <%= link_to 'BACK', invoices_path, class: "btn btn-outline-dark mb-4" %>
</div>

app/views/invoices/edit.html.erb
<%= render 'header' %>
<%= render 'navbar' %>

<div id="container" class="container-fluid">

  <% content_for :title, "Coupa Integration - Invoice" %>

  <nav class="py-4" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#"><%= link_to 'Invoice', invoices_path %></a></li>
      <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
  </nav>

  <%= form_tag(invoices_path, method: :put, class: "row g-3 mb-3") do %>
    <div class="col-md-4">
      <label for="inputSupplierIdentity" class="form-label">Supplier Identity</label>
      <%= text_field(:invoice, :SupplierIdentity, value: @identity["SupplierIdentity"], placeholder: "Supplier Identity", class: "form-control", id: "inputSupplierIdentity", readonly: true) %>
    </div>
    <div class="col-md-4">
      <label for="inputSharedSecret" class="form-label">Shared Secret</label>
      <%= text_field(:identity, :SharedSecret, value: @identity["SharedSecret"], placeholder: "Shared Secret", class: "form-control", id: "inputSharedSecret", readonly: true) %>
    </div>
    <div class="col-md-4">
      <label for="inputSupplierIdentity" class="form-label">Buyer Identity</label>
      <%= text_field(:identity, :BuyerIdentity, value: @identity["BuyerIdentity"], placeholder: "Buyer Identity", class: "form-control", id: "inputBuyerIdentity", readonly: true) %>
    </div>
    <div class="col-12">
      <button type="submit" class="btn btn-dark">SUBMIT</button>
      <%= link_to 'BACK', identity_index_path, class: "btn btn-outline-dark" %>
    </div>
  <% end %>
</div>

app/views/invoices/index.html.erb
<%= render 'header' %>
<%= render 'navbar' %>

<div id="identity-page" class="container-fluid mt-3">
    <% content_for :title, "Coupa Integration - Invoices" %>

    <h1>TABLE OF INVOICES</h1>

    <% flash.each do |type, msg| %>
        <% if type == "success" %>
            <div class="alert alert-success"> 
                <%= msg %>
            </div>
        <% else %>
            <div class="alert alert-danger"> 
                <%= msg %>
            </div>
        <% end %>
    <% end %>

    <div id="invoice-table" class="table-responsive-md table-responsive">    
        <table class="table table-striped table-hover">
            <thead class="table-dark">
                <th>ID</th>
                <th>Invoice ID</th>
                <th>From Name</th>
                <th>Remit To Name</th>
                <th>Order ID</th>
                <th>Subtotal Amount</th>
                <th>Create Date</th>
                <th colspan="4"></th>
            </thead>

            <% if @invoices.present? %>
                <tbody id="table-body">
                    <% @invoices.each do |invoice| %>
                        <tr>
                            <td><%= invoice["id"] %></th>
                            <td><%= invoice["invoiceID"] %></td>
                            <td><%= invoice["fromName"] %></td>
                            <td><%= invoice["remitToName"] %></td>
                            <td><%= invoice["orderID"] %></td>
                            <td><%= invoice["invoiceSubtotalAmount"] %></td>
                            <td><%= invoice["createDate"] %></td>
                            <td>
                                <%= link_to invoice_path(invoice["id"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Show' do %>
                                    <i class="bi bi-arrows-fullscreen" style="padding: 0 10px !important;"></i>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to invoice_invoice_items_path(invoice["id"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Invoice Items' do %>
                                    <i class="bi bi-list-ul" style="padding: 0 10px !important;"></i>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to invoice_download_path(invoice["id"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Download Invoice', target: "_blank" do %>
                                    <%= image_tag("download invoice_1.png", size: "28x35") %>
                                <% end %>
                            </td>

                            <td>
                                <%= link_to invoice_send_path(invoice["id"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Send Invoice To Coupa' do %>
                                    <%= image_tag("send invoice.png", size: "35x35") %>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>                
            <% else %>
                <tbody>
                    <div style="position: absolute; margin-top: 7rem; width: 88%; display: flex; justify-content: center; align-items: center; height: 5rem; color: #ccc; background-color: white;">
                    No Invoices
                    </div>
                </tbody>           
            <% end %>
        </table>
    </div>
</div>

app/views/invoices/invoice_items_list.html.erb
<%= render 'header' %>
<%= render 'navbar' %>

<%= @invoice_items %>

app/views/invoices/show_invoice.html.erb
<%= render 'header' %>
<%= render 'navbar' %>

<div id="container" class="container-fluid" >

    <% content_for :title, "Coupa Integration - Invoice" %>

    <nav class="py-3" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#"><%= link_to 'Invoices', invoices_path %></a></li>
            <li class="breadcrumb-item active" aria-current="page">Show</li>
        </ol>
    </nav>

    <div class="show-summary100">
        <div class="show-summary100-subtitle">
            <h1 style="border-bottom: 2px solid #000">DETAILS</h1>
        </div>

        <div class="show-summary100-content">
            <div class="content">
                <h5>ID</h5>
                <p><%= params[:id] %></p>
            </div>
            <div class="content">
                <h5>Supplier Identity</h5>
                <p><%= @invoice["fromDomain"] %></p>
            </div>
            <div class="content">
                <h5>Shared Secret</h5>
                <p><%= @invoice["fromIdentity"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["toDomain"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["toIdentity"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["senderDomain"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["senderIdentity"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["sharedSecret"] %></p>
            </div>
        </div>
    </div>



    <div class="show-summary100">
        <div class="show-summary100-subtitle">
            <h1 style="border-bottom: 2px solid #000">FROM DETAILS</h1>
        </div>

        <div class="show-summary100-content">
            <div class="content">
                <h5>Supplier Identity</h5>
                <p><%= @invoice["fromName"] %></p>
            </div>
            <div class="content">
                <h5>Shared Secret</h5>
                <p><%= @invoice["fromStreet"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["fromCity"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["fromPostalCode"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["fromCountryISOCode"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["fromCountry"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["fromTaxPrefix"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["fromTaxNumber"] %></p>
            </div>
        </div>
    </div>



    <div class="show-summary100">
        <div class="show-summary100-subtitle">
            <h1 style="border-bottom: 2px solid #000">REMIT TO DETAILS</h1>
        </div>

        <div class="show-summary100-content">
            <div class="content">
                <h5>Supplier Identity</h5>
                <p><%= @invoice["remitToName"] %></p>
            </div>
            <div class="content">
                <h5>Shared Secret</h5>
                <p><%= @invoice["remitToStreet"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["remitToCity"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["remitToPostalCode"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["remitToIsoCountryCode"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["remitToCountry"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["remitToAreaOrCityCode"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["remitToTelephoneNumber"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["remitToFaxNumber"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["remitToTaxPrefix"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["remitToTaxNumber"] %></p>
            </div>
        </div>
    </div>


       

    <div class="show-summary100">
        <div class="show-summary100-subtitle">
            <h1 style="border-bottom: 2px solid #000">INVOICE DETAILS</h1>
        </div>

        <div class="show-summary100-content">
            <div class="content">
                <h5>Supplier Identity</h5>
                <p><%= @invoice["invoiceCurrency"] %></p>
            </div>
            <div class="content">
                <h5>Shared Secret</h5>
                <p><%= @invoice["invoiceSubtotalAmount"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["invoiceTaxAmount"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["invoiceTaxDescription"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["invoiceTaxPercentageRate"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["invoiceTaxableAmount"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["invoiceTaxLocations"] %></p>
            </div>
            
        </div>
    </div>

    <div class="show-summary100">
        <div class="show-summary100-subtitle">
            <h1 style="border-bottom: 2px solid #000">EXTRA DETAILS</h1>
        </div>

        <div class="show-summary100-content">
            <div class="content">
                <h5>Supplier Identity</h5>
                <p><%= @invoice["purchaseOrderID"] %></p>
            </div>
            <div class="content">
                <h5>Shared Secret</h5>
                <p><%= @invoice["orderID"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["createDate"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["updateDate"] %></p>
            </div>
            <div class="content">
                <h5>Buyer Identity</h5>
                <p><%= @invoice["BlobID"] %></p>
            </div>
        </div>
    </div>

    <%= link_to 'BACK', identity_index_path, class: "btn btn-outline-dark mb-4" %>
</div>