config/routes.rb
Rails.application.routes.draw do
  root 'session#new'
  
  post 'login', to: 'session#create' # I will get to it when there's authenctication
  delete 'logout', to: 'session#destroy'
  
  get 'download_po/:id', to: 'order#downloadPO', as: 'download_po'

  get 'order/invoice/:id', to: 'order#invoice', as: 'order_invoice'
  post 'order/invoice/:id', to: 'order#createInvoice', as: 'create_invoice'
  post 'order', to: 'order#index'
  
  resources :identity
  resources :order
  resources :invoices do
    resources :invoice_items
    get 'download', to: 'invoices#downloadInvoice'
    get 'send', to: 'invoices#sendInvoice'
  end

  # get 'invoice_items/index'
  # get 'invoice_items/show'
  # get 'invoice_items/edit'
  # get 'invoice_items/update'
  # get 'invoice_items/index'
  # get 'invoice_items/edit'
  # get 'invoice_items/update'
  # get 'invoice_items/show'  
  get 'download_invoice/:id', to: 'order#downloadInvoice', as: 'download_invoice'
  get 'send_invoice/:id', to: 'order#sendInvoice', as: 'send_invoice'
  # resources :invoice_items
  # get 'invoices/:id/invoice_items', to: 'invoices#invoice_items_list', as: 'invoice_items_list'
  # post 'order_filter', to: 'order#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  before_action :authorize
  
  def index
    @supplier_list = current_user.supplier_list["SupplierIdentities"]
    @buyers_list = current_user.buyers_list["BuyerIdentities"]
    
    if po_filter_params.present?
      orders = current_user.po_filter(po_filter_params)["PurchaseOrders"]

      orders.each do |order|
        if order["OrderDate"].present?
          order["OrderDate"] = time_format(order["OrderDate"])
        end
      end

      @orders = reverse_list(orders)
    else
      orders = current_user.p_orders["PurchaseOrders"]

      orders.each do |order|
        if order["OrderDate"].present?
          order["OrderDate"] = time_format(order["OrderDate"])
        end
      end

      @orders = reverse_list(orders)
    end
  end

  def create
    if po_filter_params.present?
      @orders = po_filter_params
    else
      orders = current_user.p_orders["PurchaseOrders"]

      orders.each do |order|
        if order["OrderDate"].present?
          order["OrderDate"] = time_format(order["OrderDate"])
        end
      end

      @orders = reverse_list(orders)
    end
  end

  def downloadPO
    file = current_user.po_download(params[:id])
    send_data file, filename: "PO_ID_#{params[:id]}.xml", disposition: 'download'
  end
  
  def downloadInvoice
    # WE MUST USE AJAX HERE!!
    unless current_user.invoice_get(params[:id]).include? ("Error")
      file = current_user.invoice_get(params[:id])
      send_data file, filename: "INVOICE_ID_#{params[:id]}.xml", disposition: 'download'
    else
      flash[:danger] = "No Invoice file found. Ensure that you create an Invoice first."
      redirect_to order_index_path
    end
  end

  def invoice;
  end

  def createInvoice
    current_user.invoice_create(params[:id], po_params)
    redirect_to order_index_path
  end

  def sendInvoice
    @invoice = current_user.invoice_send(params[:id])
    
    unless @invoice["Error"].present?
      flash[:success] = 'Invoice successfully sent'
    else
      flash[:danger] = "Ensure that you have created an Invoice before Sending an invoice to Coupa"
    end
    
    redirect_to order_index_path
  end

  private
  
  def time_format(time_string)
    temp_arr = time_string.split('T')
    temp_arr2 = temp_arr[1].split(':')
    temp_str = temp_arr[0] + ", " + temp_arr2[0] + ":" + temp_arr2[1]
    temp_str
  end

  def reverse_list(list)
    list.reverse()
  end

  def po_params
    params.require(:order).permit!
  end

  def po_filter_params
    params.permit(:BuyerIdentity, :SupplierIdentity, :OrderID, :fromDate, :toDate)
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/order/_order_filter_form.html.erb
<%= form_with( url: order_index_path, method: :post, remote: true) do |form| %>
    <div class="menu">
        <div>
            <h4>Filtering</h4>
        </div>

        <div>
            <div class="input-field">
                <label for="BuyerIdentity">Buyer Identity:</label>
                <select name="BuyerIdentity" id="BuyerIdentity" class="form-select" aria-label="Default select example">
                    <option value="test1" selected>test1</option>
                </select>
            </div>

            <div class="input-field">
                <label for="SupplierIdentity">Supplier ID:</label>        
                <select name="SupplierIdentity" id="SupplierIdentity" class="form-select" aria-label="Default select example">
                    <option value="test1" selected>test1</option>
                </select>
            </div>

            <div class="input-field">
                <label for="inputOrderID" class="form-label">Order ID</label>
                <%= form.number_field(:OrderID, placeholder: "Order ID", class: "form-control", id: "inputOrderID") %>
            </div>

            <div class="input-field">
                <label for="inputFromDate" class="form-label">From-Date</label>
                <%= form.date_field(:fromDate, min: "2022-01-01", max: Date.today) %>

                <label for="inputToDate" class="form-label">To-Date</label>
                <%= form.date_field(:toDate, min: "2022-01-01", max: Date.today) %>
            </div>
        </div>

        <div class="btns">
            <div class="cancel-btn">
                <a href="#" style="color: red !important;">Clear Filtering</a>
            </div>

            <div class="accept-btn">
                <!-- 
                <button type="button" class="btn btn-outline-dark">Cancel</button>
                <button type="button" class="btn btn-dark">Accept</button> 
                <input type="submit" class="btn btn-dark" value="Accept"> -->

                <%= button_tag("Accept", :class => "btn btn-dark", :id => "loader-btn") %> 
                <%= form.submit "Accept", :class => "btn btn-dark", :id => "loader-btn" %> 
            </div>
        </div>
    </div>
<% end %>

app/views/order/index.html.erb
<% content_for :title, "Coupa Integration - Purchase Orders" %>

<%= render 'header' %>
<%= render 'navbar' %>

<div id="order-page" class="container-fluid mt-3">

    <h1 class="mb-3">TABLE OF PURCHASE ORDERS</h1>

    <% flash.each do |type, msg| %>
        <% if type == "success" %>
            <div class="alert alert-success"> 
                <%= msg %>
            </div>
        <% else %>
            <div class="alert alert-danger"> 
                <%= msg %>
            </div>
        <% end %>
    <% end %>

    <div class="action mb-3">
        <div class="profile">
            <button class="btn btn-dark" id="profile-btn">Filter <i class="bi bi-filter" style="color: white !important"></i></button>
        </div>

        <%= form_tag(order_path, method: :post) do %>
            <div class="menu">
                <div>
                    <h4>Filtering</h4>
                </div>

                <div>
                    <div class="input-field">
                        <label for="BuyerIdentity">Buyer Identity:</label>
                        <select name="BuyerIdentity" id="BuyerIdentity" class="form-select" aria-label="Default select example">
                            <option value="" selected>Select B ID</option>
                            <%= @buyers_list.each do |buyer| %>
                                <option value="<%= buyer["Identity"] %>"><%= buyer["Identity"] %></option>
                            <% end %>
                        </select>
                    </div>

                    <div class="input-field">
                        <label for="SupplierIdentity">Supplier ID:</label>        
                        <select name="SupplierIdentity" id="SupplierIdentity" class="form-select" aria-label="Default select example">
                            <option value="" selected>Select Sup ID</option>

                            <%= @supplier_list.each do |supplier| %>
                                <option value="<%= supplier["Identity"] %>"><%= supplier["Identity"] %></option>
                            <% end %>
                        </select>
                    </div>

                    <div class="input-field">
                        <label for="inputOrderID" class="form-label">Order ID</label>
                        <%= text_field_tag(:OrderID, '', placeholder: "Order ID", class: "form-control", id: "inputOrderID") %>
                    </div>

                    <div class="input-field">
                        <label for="inputFromDate" class="form-label">From-Date</label>
                        <%= date_field_tag(:fromDate) %>

                        <label for="inputToDate" class="form-label">To-Date</label>
                        <%= date_field_tag(:toDate) %>
                    </div>
                </div>

                <div class="btns">
                    <div class="clear-btn">
                        <%= link_to 'Clear All Filterings', order_index_path, :style => "color: red !important" %>
                    </div>

                    <div class="accept-btn">
                        <!-- 
                        <button type="button" class="btn btn-outline-dark">Cancel</button>
                        <button type="button" class="btn btn-dark">Accept</button> 
                        <input type="submit" class="btn btn-dark" value="Accept"> -->

                        <p class="btn btn-outline-dark" id="cancel-btn">Cancel</p>
                        <%= button_tag("Accept", :class => "btn btn-dark", :id => "loader-btn") %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>


    <div id="order-table" class="table-responsive-md">
        <table class="table table-striped table-hover">
            <thead class="table-dark">
                <th>ID</th>
                <th>From Identity</th>
                <th>To Identity</th>
                <th>Order ID</th>
                <th>Order Date</th>
                <th></th>
                <th></th>
            </thead>

            <% if @orders.present? %>
                <tbody id="table-body">
                    <% @orders.each do |order| %>
                        <tr>
                            <td><%= order["ID"] %></td>
                            <td><%= order["FromIdentity"] %></td>
                            <td><%= order["ToIdentity"] %></td>
                            <td><%= order["OrderID"] %></td>
                            <td><%= order["OrderDate"] %></td>
                            <td>
                                <%= link_to download_po_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Download Purchase Order', target: '_blank' do %>
                                    <!-- <i class="bi bi-file-earmark-arrow-down"></i> -->
                                    <i class="bi bi-download"></i>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to order_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Create Invoice' do %>
                                    <i class="bi bi-cloud-plus"></i>
                                <% end %>
                            </td>

                            <!--
                            <td>
                                <%= link_to download_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, remote: true, title: 'Download Invoice' do %>
                                    <i class="bi bi-cloud-arrow-down"></i>
                                    <!-- STILL GOTTA LOOK INTO IT 
                                <% end %>
                            </td>
                            <td>
                                <%= link_to send_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Send Invoice to Coupa' do %>
                                    <i class="bi bi-cloud-arrow-up"></i>
                                <% end %> -->
                            </td>
                        </tr>
                    <% end %>
                </tbody>                
            <% else %>
                <tbody>
                    <div style="position: absolute; margin-top: 7rem; width: 88%; display: flex; justify-content: center; align-items: center; height: 5rem; color: #ccc; background-color: white;">
                        No Purchase Orders
                    </div>
                </tbody>           
            <% end %>
        </table>        
    </div>
</div>


<%= javascript_pack_tag 'ajax_submit' %>
<%= javascript_pack_tag 'dropdown' %>
<%= javascript_pack_tag 'tooltip' %>

app/views/order/invoice.html.erb
<% content_for :title, "Coupa Integration - Purchase Orders" %>

<%= render 'header' %>
<%= render 'navbar' %>

<div id="container" class="container-fluid mt-3">

    <nav class="py-3" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#"><%= link_to 'Orders', order_index_path %></a></li>
            <li class="breadcrumb-item active" aria-current="page">Create Invoice</li>
        </ol>
    </nav>

    <%= form_tag(create_invoice_path, method: :post, class: "row g-3 mb-3") do %>
        <div class="col-md-4">
            <label for="inputPoID" class="form-label">Purchase Order ID</label>
            <%= text_field(:order, :PoID, value: params[:id] , placeholder: "Purchase Order ID", class: "form-control", id: "inputPoID", disabled: true) %>
        </div>

        <div class="col-md-4">
            <label for="inputInvoiceID" class="form-label">Invoice ID</label>
            <%= text_field(:order, :Invoice, placeholder: "Invoice ID", class: "form-control", id: "inputInvoiceID", required: true) %>
        </div>
    
        <div class="col-12">
            <button type="submit" class="btn btn-dark">SUBMIT</button>
            <%= link_to 'BACK', order_index_path, class: "btn btn-outline-dark" %>
        </div>
    <% end %>
</div>

app/views/order/sendInvoice.html.erb
<%= @dsfdg %>

<!--
<div id="fliter-wrapper" class"d-flex flex-row-reverse">
    <a href="#" id="navbarDropdown" role="button" data-toggle="dropdown" class="dropdown-toggle nav-link">Filter</a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="#">KANYE WEST</a>
    </div>
</div> 

<div id="fliter-wrapper" class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dropdown button
    </button>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
    </div>
</div>

<div class="dropdown show">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dropdown link
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
    </div>
</div> -->

<!-- 
<div>
    <label for="">Supplier Identity</label>
    <input type="text" placeholder="Supplier Identity">
</div>

<div>                
    <label for="">Order ID</label>
    <input type="number" placeholder="OrderID">
</div>

<div>
    <label for="">Buyer Identity</label>
    <input type="text" placeholder="Buyer Identity">
</div>
-->

<!--
    <div id="fliter-wrapper" class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown button
        </button>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
        </div>
    </div>

    <div class="filter-container">
        <div class="filter-content">
            <div class="col-md-8">
                <label for="inputSupplierIdentity" class="form-label">Supplier Identity</label>
                <%= text_field(:identity, :SupplierIdentity, placeholder: "SupplierIdentity", class: "form-control", id: "inputSupplierIdentity", required: true) %>
            </div>

            <div class="col-md-8">
                <label for="inputBuyerIdentity" class="form-label">Buyer Identity</label>
                <%= text_field(:identity, :BuyerIdentity, placeholder: "BuyerIdentity", class: "form-control", id: "inputBuyerIdentity", required: true) %>
            </div>
            
            <div class="col-md-8">
                <label for="inputOrderID" class="form-label">Order ID</label>
                <%= number_field(:identity, :inputOrderID, placeholder: "Order ID", class: "form-control", id: "inputOrderID", required: true) %>
            </div>
        </div>

        <div class="filter-buttons d-flex align-items-center justify-content-center">
            <div class="filtering-cancel-btn">
                <button class="btn btn-outline-danger">Clear all filtering</button>
            </div>

            <div class="filtering-accept-btn">
                <button class="btn btn-outline-dark">CANCEL</button>
                <button class="btn btn-dark">Apply</button>
            </div>
        </div>
    </div>
-->

<!--
    <div id="order-table" class="table-responsive-md">
        <table class="table table-striped table-hover">
            <thead class="table-dark">
                <th>ID</th>
                <th>FromIdentity</th>
                <th>ToIdentity</th>
                <th>SharedSecret</th>
                <th>Order ID</th>
                <th>OrderDate</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
                <% @orders.each do |order| %>
                    <tr>
                        <td><%= order["ID"] %></td>
                        <td><%= order["FromIdentity"] %></td>
                        <td><%= order["ToIdentity"] %></td>
                        <td><%= order["SharedSecret"] %></td>
                        <td><%= order["OrderID"] %></td>
                        <td><%= order["OrderDate"] %></td>
                        <td>
                            <%= link_to download_po_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Download Purchase Order', target: '_blank' do %>
                                <i class="bi bi-file-earmark-arrow-down"></i>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to order_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Create Invoice' do %>
                                <i class="bi bi-cloud-plus"></i>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to download_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Download Invoice', target: '_blank' do %>
                                <i class="bi bi-cloud-arrow-down"></i>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to send_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Send Invoice to Coupa' do %>
                                <i class="bi bi-cloud-arrow-up"></i>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>        
    </div>
</div>
-->

app/views/order/sendInvoice.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'sendInvoice') %>");
$("#modal-window").modal();

<!--
<%# @orders ? 
    <tbody id="table-body">
        <% @orders.each do |order| %>
            <tr>
                <td><%= order["ID"] %></td>
                <td><%= order["FromIdentity"] %></td>
                <td><%= order["ToIdentity"] %></td>
                <td><%= order["SharedSecret"] %></td>
                <td><%= order["OrderID"] %></td>
                <td><%= order["OrderDate"] %></td>
                <td>
                    <%= link_to download_po_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Download Purchase Order', target: '_blank' do %>
                        <!-- <i class="bi bi-file-earmark-arrow-down"></i> -->
                        <i class="bi bi-download"></i>
                    <% end %>
                </td>
                <td>
                    <%= link_to order_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Create Invoice' do %>
                        <i class="bi bi-cloud-plus"></i>
                    <% end %>
                </td>
                <td>
                    <%= link_to download_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Download Invoice', target: '_blank' do %>
                        <i class="bi bi-cloud-arrow-down"></i>
                    <% end %>
                </td>
                <td>
                    <%= link_to send_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Send Invoice to Coupa' do %>
                        <i class="bi bi-cloud-arrow-up"></i>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody> : <tbody id="table-body"><div class="bg-light navbar-light row">No Identities</div></tbody> %>

<tbody>
    <% @orders.each do |order| %>
        <tr>
            <td><%= order["ID"] %></td>
            <td><%= order["FromIdentity"] %></td>
            <td><%= order["ToIdentity"] %></td>
            <td><%= order["SharedSecret"] %></td>
            <td><%= order["OrderID"] %></td>
            <td><%= order["OrderDate"] %></td>
            <td>
                <%= link_to download_po_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Download Purchase Order', target: '_blank' do %>
                    <!-- <i class="bi bi-file-earmark-arrow-down"></i> -->
                    <i class="bi bi-download"></i>
                <% end %>
            </td>
            <td>
                <%= link_to order_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Create Invoice' do %>
                    <i class="bi bi-cloud-plus"></i>
                <% end %>
            </td>
            <td>
                <%= link_to download_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Download Invoice', target: '_blank' do %>
                    <i class="bi bi-cloud-arrow-down"></i>
                <% end %>
            </td>
            <td>
                <%= link_to send_invoice_path(order["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Send Invoice to Coupa' do %>
                    <i class="bi bi-cloud-arrow-up"></i>
                <% end %>
            </td>
        </tr>
    <%# end %>
</tbody>
-->

<!--
            <tbody id="table-body">
                <% @identities.each do |identity| %>
                    <tr>
                        <td><%= identity["ID"] %></th>
                        <td><%= identity["SupplierIdentity"] %></td>
                        <td><%= identity["SharedSecret"] %></td>
                        <td><%= identity["BuyerIdentity"] %></td>
                        <td><%= identity["CreateDate"] %></td>
                        <td>
                            <%= link_to identity_path(identity["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Show' do %>
                                <i class="bi bi-arrows-fullscreen"></i>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to edit_identity_path(identity["ID"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Edit' do %>
                                <i class="bi bi-pencil"></i>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to identity_path(identity["ID"]), method: :delete, data: { toggle: 'tooltip', placement: "top", confirm: "Are you sure?" }, title: 'Delete' do %>
                                <i class="bi bi-trash"></i>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
            -->

app/views/order/updatePO.html.erb
<%= @params %>
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  ***** Not Wokring *****
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

<%= javascript_pack_tag 'tooltip' %>
<!--
<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>
<td><%# link_to 'Download PO', download_po_path(order["ID"]), class: "btn btn-success", style: "color: white !important", target: '_blank' %></td>
<td><%= link_to 'Create Invoice', order_invoice_path(order["ID"]), class: "btn btn-outline-success" %></td>
<td><%= link_to 'Download Invoice', download_invoice_path(order["ID"]), class: "btn btn-outline-success", target: '_blank' %></td>
<td><%= link_to 'Send Invoice', order_index_path, class: "btn btn-outline-success bi bi-cloud-arrow-up-fill", remote: true %></td>
 <td><%# link_to 'Send Invoice', send_invoice_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary'}  %></td> -->