config/routes.rb
Rails.application.routes.draw do
  root 'session#new'
  
  post 'login', to: 'session#create' # I will get to it when there's authenctication
  delete 'logout', to: 'session#destroy'
  
  get 'download_po/:id', to: 'order#downloadPO', as: 'download_po'

  get 'order/invoice/:id', to: 'order#invoice', as: 'order_invoice'
  post 'order/invoice/:id', to: 'order#createInvoice', as: 'create_invoice'
  post 'order', to: 'order#index'
  
  resources :identity
  resources :order
  resources :invoices do
    resources :invoice_items
    get 'download', to: 'invoices#downloadInvoice'
    get 'send', to: 'invoices#sendInvoice'
  end

  # get 'invoice_items/index'
  # get 'invoice_items/show'
  # get 'invoice_items/edit'
  # get 'invoice_items/update'
  # get 'invoice_items/index'
  # get 'invoice_items/edit'
  # get 'invoice_items/update'
  # get 'invoice_items/show'  
  get 'download_invoice/:id', to: 'order#downloadInvoice', as: 'download_invoice'
  get 'send_invoice/:id', to: 'order#sendInvoice', as: 'send_invoice'
  # resources :invoice_items
  # get 'invoices/:id/invoice_items', to: 'invoices#invoice_items_list', as: 'invoice_items_list'
  # post 'order_filter', to: 'order#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/invoice_items_controller.rb
class InvoiceItemsController < ApplicationController
  before_action :authorize
  
  def index
    @invoice_items = current_user.invoiceItems_of_invoice(params[:invoice_id])["InvoiceItems"]
  end

  def show
    @invoice_item = current_user.invoiceLineItems_get(params[:id])["InvoiceItem"]
    @invoice_item["createDate"] = time_format(@invoice_item["createDate"]) if @invoice_item["createDate"].present?
    @invoice_item["updateDate"] = time_format(@invoice_item["updateDate"]) if @invoice_item["updateDate"].present?
  end

  def edit
    @invoice_item = current_user.invoiceLineItems_get(params[:id])["InvoiceItem"]
  end

  def update
    invoiceID = current_user.invoiceLineItems_get(params[:id])["InvoiceItem"]["invoiceID"]
    @response = current_user.invoice_item_update( params[:id], invoiceID, invoice_items_params )
    redirect_to invoice_invoice_items_path(invoiceID: @response["invoiceID"])
  end

  private

  def invoice_items_params
    params.require(:invoice_item).permit!
  end

  def time_format(time_string)
    temp_arr = time_string.split('T')
    temp_arr2 = temp_arr[1].split(':')
    temp_str = temp_arr[0] + ", " + temp_arr2[0] + ":" + temp_arr2[1]
    temp_str
  end 
end

app/helpers/invoice_items_helper.rb
module InvoiceItemsHelper
end

app/views/invoice_items/edit.html.erb
<%= render 'header' %>
<%= render 'navbar' %>

<div id="container" class="container-fluid">

  <% content_for :title, "Coupa Integration - Invoice Item" %>

  <nav class="py-4" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#"><%= link_to 'Invoice Items', invoice_invoice_items_path(@invoice_item["invoiceID"]) %></a></li>
      <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
  </nav>

  <%= form_tag(invoice_invoice_item_path, method: :put, class: "row g-3 mb-3") do %>
    <div class="col-md-4">
      <label for="inputUnitPrice" class="form-label">Unit Price</label>
      <%= text_field(:invoice_item, :UnitPrice, value: @invoice_item["unitPrice"], placeholder: "Unit Price", class: "form-control", id: "inputUnitPrice") %>
    </div>
    <div class="col-md-4">
      <label for="inputQuantity" class="form-label">Quantity</label>
      <%= text_field(:invoice_item, :Quantity, value: @invoice_item["quantity"], placeholder: "Quantity", class: "form-control", id: "inputQuantity") %>
    </div>

    <div class="col-12">
      <button type="submit" class="btn btn-dark">SUBMIT</button>
      <%= link_to 'BACK', invoice_invoice_items_path(@invoice_item["invoiceID"]), class: "btn btn-outline-dark" %>
    </div>
  <% end %>
</div>

app/views/invoice_items/index.html.erb
<%= render 'header' %>
<%= render 'navbar' %>

<div id="identity-page" class="container-fluid mt-3">
    <% content_for :title, "Coupa Integration - Invoice Items" %>

    <h1>TABLE OF INVOICES ITEMS</h1>

    <div id="invoice-items-table" class="table-responsive-md table-responsive">    
        <table class="table table-striped table-hover">
            <thead class="table-dark">
                <th>ID</th>
                <th>Invoice ID</th>
                <th>Invoice Item Description</th>
                <th>Item Unit Of Measure</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th colspan="2"></th>
            </thead>

            <% if @invoice_items.present? %>
                <tbody id="table-body">
                    <% @invoice_items.each do |invoice_item| %>
                        <tr>
                            <td><%= invoice_item["id"] %></th>
                            <td><%= invoice_item["invoiceID"] %></td>
                            <td><%= invoice_item["invoiceItemDescription"] %></td>
                            <td><%= invoice_item["itemUnitOfMeasure"] %></td>
                            <td><%= invoice_item["quantity"] %></td>
                            <td><%= invoice_item["unitPrice"] %></td>
                            <td>
                                <%= link_to invoice_invoice_item_path(id: invoice_item["id"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Show' do %>
                                    <i class="bi bi-arrows-fullscreen" style="padding: 0 10px !important;"></i>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to edit_invoice_invoice_item_path(id: invoice_item["id"]), data: { toggle: 'tooltip', placement: "top" }, title: 'Edit' do %>
                                    <i class="bi bi-pencil" style="padding: 0 10px !important;"></i>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>                
            <% else %>
                <tbody>
                    <div style="position: absolute; margin-top: 7rem; width: 88%; display: flex; justify-content: center; align-items: center; height: 5rem; color: #ccc; background-color: white;">
                    No Invoice Items
                    </div>
                </tbody>           
            <% end %>
        </table>

        <%= link_to 'BACK', invoices_path, class: "btn btn-outline-dark" %>
    </div>
</div>

app/views/invoice_items/show.html.erb
<%= render 'header' %>
<%= render 'navbar' %>

<div id="container" class="container-fluid" >

    <% content_for :title, "Coupa Integration - Invoice Items" %>

    <nav class="py-3" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#"><%= link_to 'Invoice Items', invoice_invoice_items_path(@invoice_item["invoiceID"]) %></a></li>
            <li class="breadcrumb-item active" aria-current="page">Show</li>
        </ol>
    </nav>

    <div class="show-summary100">
        <div class="show-summary100-subtitle">
            <h1 style="border-bottom: 2px solid #000">DETAILS</h1>
        </div>

        <div class="show-summary100-content row row-cols-1 row-cols-sm-2 row-cols-md-4">
            <div class="content col-md-3">
                <h5>ID</h5>

                <% if @invoice_item["id"].present? %>
                    <p><%= @invoice_item["id"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Invoice ID</h5>

                <% if @invoice_item["invoiceID"].present? %>
                    <p><%= @invoice_item["invoiceID"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Invoice Line Number</h5>

                <% if @invoice_item["invoiceLineNumber"].present? %>
                    <p><%= @invoice_item["invoiceLineNumber"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Quantity</h5>
                <p><%= @invoice_item["quantity"] %></p>

                <% if @invoice_item["quantity"].present? %>
                    <p><%= @invoice_item["quantity"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Invoice Item Currency</h5>

                <% if @invoice_item["invoiceItemCurrency"].present? %>
                    <p><%= @invoice_item["invoiceItemCurrency"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Unit Price</h5>

                <% if @invoice_item["unitPrice"].present? %>
                    <p><%= @invoice_item["unitPrice"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Invoice Item Description</h5>

                <% if @invoice_item["invoiceItemDescription"].present? %>
                    <p><%= @invoice_item["invoiceItemDescription"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Item Tax Percentage</h5>

                <% if @invoice_item["itemTaxPercentage"].present? %>
                    <p><%= @invoice_item["itemTaxPercentage"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>

            <div class="content col-md-3">
                <h5>Item Tax Amount</h5>

                <% if @invoice_item["itemTaxAmount"].present? %>
                    <p><%= @invoice_item["itemTaxAmount"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Item Unit Of Measure</h5>

                <% if @invoice_item["itemUnitOfMeasure"].present? %>
                    <p><%= @invoice_item["itemUnitOfMeasure"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Item Tax Category</h5>

                <% if @invoice_item["itemTaxCategory"].present? %>
                    <p><%= @invoice_item["itemTaxCategory"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Item Tax Description</h5>

                <% if @invoice_item["itemTaxDescription"].present? %>
                    <p><%= @invoice_item["itemTaxDescription"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Create Date</h5>


                <% if @invoice_item["createDate"].present? %>
                    <p><%= @invoice_item["createDate"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
            <div class="content col-md-3">
                <h5>Update Date</h5>

                <% if @invoice_item["updateDate"].present? %>
                    <p><%= @invoice_item["updateDate"] %></p>
                <% else %>
                    <p class="null-value">NULL</p>
                <% end %>
            </div>
        </div>
    </div>

    <%= link_to 'BACK', invoice_invoice_items_path(@invoice_item["invoiceID"]), class: "btn btn-outline-dark mb-4" %>
</div>

app/views/invoice_items/update.html.erb
<h1>InvoiceItems#update</h1>
<p>Find me in app/views/invoice_items/update.html.erb</p>

<%= @response %>