config/routes.rb
Rails.application.routes.draw do
  root 'session#new'
  
  post 'login', to: 'session#create' # I will get to it when there's authenctication
  delete 'logout', to: 'session#destroy'
  
  get 'download_po/:id', to: 'order#downloadPO', as: 'download_po'

  get 'order/invoice/:id', to: 'order#invoice', as: 'order_invoice'
  post 'order/invoice/:id', to: 'order#createInvoice', as: 'create_invoice'
  post 'order', to: 'order#index'
  
  resources :identity
  resources :order
  resources :invoices do
    resources :invoice_items
    get 'download', to: 'invoices#downloadInvoice'
    get 'send', to: 'invoices#sendInvoice'
  end

  # get 'invoice_items/index'
  # get 'invoice_items/show'
  # get 'invoice_items/edit'
  # get 'invoice_items/update'
  # get 'invoice_items/index'
  # get 'invoice_items/edit'
  # get 'invoice_items/update'
  # get 'invoice_items/show'  
  get 'download_invoice/:id', to: 'order#downloadInvoice', as: 'download_invoice'
  get 'send_invoice/:id', to: 'order#sendInvoice', as: 'send_invoice'
  # resources :invoice_items
  # get 'invoices/:id/invoice_items', to: 'invoices#invoice_items_list', as: 'invoice_items_list'
  # post 'order_filter', to: 'order#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :authorize
    helper_method :current_user
    helper_method :logged_in?

    rescue_from ActionController::InvalidAuthenticityToken, with: :user_not_authorized

    def user_not_authorized
        redirect_to root_path
    end

    def logged_in?
        !current_user.nil?
    end

    def redirect_if_logged_in?
        redirect_to order_index_path if logged_in?
    end

    def current_user
        @current_user ||= begin
            User.new(session[:user]) if session[:user]
        end
    end

    def authorize
        return if logged_in?
        session[:return_to] = request.url
        redirect_to root_path
    end

    def set_current_user(user)
        session[:user] = user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<nav id="header" class="navbar navbar-expand-sm navbar-light bg-light border-bottom border-dark">
    <div class="container-fluid">
        <h1><a class="navbar-brand" href="<%= order_index_path %>" style="font-weight: 600">SCP</a></h1>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <%= link_to 'Logout', logout_path, :method => :delete, :class => 'nav-link', :style => "color: red !important", :data => { :confirm => 'Are you sure?'} %>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/application/_navbar.html.erb
<!-- Navbar -->
<div id="navbar" class="container-fluid">
    <ul id="navbar" class="nav">
        <li class="nav-item">
            <%= active_link_to 'Purchase Orders', order_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= active_link_to 'Identities', identity_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= active_link_to 'Invoices', invoices_path, class: "nav-link" %>
        </li>
    </ul>
    <br>
</div>